### ISSUE TITLE
delete clusters without remembering the names

### ISSUE THREAD

**Issue by Petahhh** [atmandhol/tappr#11]
# Problem

I often create clusters with specific purposes and label them accordingly. E.g.:
* tanzusc-123-bug
* tap-1-5
* hostname-problem

I'd like to delete these clusters but don't always remember the spelling of the clusters

# Request

It'll be a minor convenience to have either the command

`tappr cluster delete` that prompts me to choose which cluster to delete

or 

`tappr cluster list` to quickly print the cluster names I created

**Comment by atmandhol** [comment]
Implemented in https://github.com/atmandhol/tappr/commit/d0e0341eb3aea3232257adcdc5e48da7d72e7897
