### ISSUE TITLE
gke cluster used-by label

### ISSUE THREAD

**Issue by Petahhh** [atmandhol/tappr#12]
# Problem

When doing cluster clean up there are many clusters in a team project. Sometimes based on the name of the cluster it's unclear who created it. Knowing who created it can helps us make decisions on if it's safe to delete (e.g. we can ping them, if they've left the company we can just delete it)

# Request

By default (maybe set via a config property), when I create clusters it'd be nice if the label `used-by: Peter` was added to make it easier to clean up

**Comment by atmandhol** [comment]
Great idea! i'll add a `used-by` label in the GKE cluster creation and it can take your tanzunet email from tappr init config. Does that suffice? did you any other fields in mind that might help?

**Comment by Petahhh** [comment]
That would be awesome!
